version: '3.4'

services:
    
  bookingdb:
    container_name: bookingdb
    environment:
        MSSQL_SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
        
    restart: always
    ports:
        - "1433:1433"

  paymentdb:
    container_name: paymentdb
    restart: always
    ports:
      - "6379:6379"

  booking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:SqlServerConnstr= Server=bookingdb;Database=BookingDb; User Id= SA ;Password= SwN12345678"
    depends_on:
      - bookingdb
    ports:
      - "2004:80"

  payment.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=paymentdb:6379"
    depends_on:
      - paymentdb
    ports:
      - "2006:80"

