version: '3.4'

services:
  moviedb:
    image: mongo
  
  movies.api:
    image: ${DOCKER_REGISTRY-}moviesapi
    build:
      context: .
      dockerfile: Services/Movies/Movies.API/Dockerfile

volumes:
  mongo_data:
  