version: '3.4'

services:
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  movies.api:
    container_name: movies.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://moviedb:27017"
    
    depends_on:
      - moviedb
    ports:
      - "2000:80"
