version: '3.4'

services:
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 

  bevaragedb:
    container_name: bevaragedb
    restart: always
    ports:
      - "6379:6379" 

  movies.api:
    container_name: movies.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://moviedb:27017"
    
    depends_on:
      - moviedb
    ports:
      - "2000:80"

  bevaregas:
    container_name: bevaregas
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=bevaragedb:6379"
    depends_on:
      - bevaragedb 
    ports:
      - "2001:80"

